workflows:
  android:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1

    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Install dependencies
        script: npm install

      - name: Build
        script: npm run build-android

    artifacts:
      - android/app/build/debug/**/*.apk
